# Generated by Django 3.1.7 on 2021-06-10 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('e_firstname', models.CharField(max_length=30)),
                ('e_lastname', models.CharField(max_length=30)),
                ('e_phoneno', models.IntegerField(default=False)),
                ('e_salary', models.IntegerField()),
            ],
        ),
    ]
