# Generated by Django 3.1.7 on 2021-06-10 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='e_firstname',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='e_lastname',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='e_phoneno',
            new_name='phone_number',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='e_salary',
            new_name='salary',
        ),
    ]
